FROM fedora

RUN  dnf upgrade -y \
	&& dnf -y groupinstall "Development Tools" \
	&& dnf -y install make autoconf java-latest-openjdk java-latest-openjdk-devel zip unzip file findutils which libXtst-devel libXt-devel libXrender-devel libXi-devel cups-devel freetype-devel alsa-lib-devel libffi-devel gcc-c++ libXtst-devel libXrandr-devel fontconfig-devel mercurial

RUN mkdir /jdk
VOLUME /jdk
WORKDIR /jdk
COPY startup.sh /

ENTRYPOINT ["/startup.sh"]
